#include<iostream>                                                                                                                                                                                                                                                                                                                                                                                                                         
#include<string.h>                                                                                                                                                                                                                                                                                                                                                                                                                         
using namespace std;                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                         
struct data                                                                                                                                                                                                                                                                                                                                                                                                                        
{                                                                                                                                                                                                                                                                                                                                                                                                                          
    int num;                                                                                                                                                                                                                                                                                                                                                                                                                           
    string name;                                                                                                                                                                                                                                                                                                                                                                                                                           
};       

int x = 10;
int * ptr = &x;
struct data data1;                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                         
class Upper{                                                                                                                                                                                                                                                                                                                                                                                                                           
    public:                                                                                                                                                                                                                                                                                                                                                                                                                        
    void insert(){                                                                                                                                                                                                                                                                                                                                                                                                                         
        cout<<"Enter a number:";                                                                                                                                                                                                                                                                                                                                                                                                                           
        cin>>::data1.num;                                                                                                                                                                                                                                                                                                                                                                                                                          
        cout<<"Enter name:";                                                                                                                                                                                                                                                                                                                                                                                                                        
        cin>>::data1.name;                                                                                                                                                                                                                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                
    void display(){                                                                                                                                                                                                                                                                                                                                                                                                                        
        cout<<"Number:"<<::data1.num<<endl;                                                                                                                                                                                                                                                                                                                                                                                                                        
        cout<<"Name:"<<::data1.name<<endl;                                                                                                                                                                                                                                                                                                                                                                                                                         
    }              
    void change(){
        // cout<<::ptr<<endl;
        cout<<::x<<endl;
    }                                                                                                                                                                                                                                                                                                                                                                                                            
};                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                         
int main(){                                                                                                                                                                                                                                                                                                                                                                                                                        
    Upper obj;                                                                                                                                                                                                                                                                                                                                                                                                                         
    obj.insert();                                                                                                                                                                                                                                                                                                                                                                                                                          
    obj.display();         
    obj.change();
    return 0;                                                                                                                                                                                                                                                                                                                                                                                                                          
}